name: Dokcer Build and push

on:
  push:
    tags: '*'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Extract Tag
        id: extract-tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          TAG: ${{ env.TAG }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traing-python-app:${TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/traing-python-app:${TAG}
